### ISSUE TITLE
SSL certificate for athtech.run is not valid

### ISSUE THREAD

**Issue by tripu** [openath/athtech#2]
@espinr, @captainrobbo:
the cert has `*.github.com` as the common name (CN), but the custom domain is `athtech.run`

Perhaps [&ldquo;troubleshooting custom domains, &sect; HTTPS errors&rdquo;](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) will help with this?

**Comment by espinr** [comment]
Solved. Thanks
